/**
 * drive-tool.ts
 * Uploads MR review reports as Markdown files to Google Drive.
 *
 * Setup:
 *   1. Enable the Drive API in your Google Cloud project.
 *   2. Share the target folder with your service account email.
 *   3. Set GOOGLE_SERVICE_ACCOUNT_JSON and GOOGLE_DRIVE_FOLDER_ID in .env.
 *
 * Google Drive API v3 docs: https://developers.google.com/drive/api/v3
 */

import { google } from "googleapis";
import { Readable } from "stream";
import type { AnalysisRecord } from "./db.js";

// ---------------------------------------------------------------
// Types
// ---------------------------------------------------------------
export interface DriveUploadResult {
  fileId: string;
  fileName: string;
  webViewLink: string;
  folderId: string;
}

// ---------------------------------------------------------------
// Auth Helper (reuses same service account as sheets-tool)
// ---------------------------------------------------------------
function getAuth() {
  const raw = process.env.GOOGLE_SERVICE_ACCOUNT_JSON;
  if (!raw) {
    throw new Error(
      "GOOGLE_SERVICE_ACCOUNT_JSON .env mein set nahi hai."
    );
  }

  let credentials: object;
  try {
    credentials = JSON.parse(raw);
  } catch {
    throw new Error("GOOGLE_SERVICE_ACCOUNT_JSON valid JSON nahi hai.");
  }

  return new google.auth.GoogleAuth({
    credentials,
    scopes: [
      "https://www.googleapis.com/auth/drive.file",
    ],
  });
}

// ---------------------------------------------------------------
// Main Export
// ---------------------------------------------------------------
export async function saveReportToDrive(
  record: AnalysisRecord,
  folderId?: string
): Promise<DriveUploadResult> {
  const folder = folderId ?? process.env.GOOGLE_DRIVE_FOLDER_ID;
  if (!folder) {
    throw new Error("GOOGLE_DRIVE_FOLDER_ID .env mein set nahi hai.");
  }

  const auth = getAuth();
  const drive = google.drive({ version: "v3", auth });

  const reportContent = buildMarkdownReport(record);
  const fileName = buildFileName(record);

  // Upload as plain text (Markdown)
  const fileStream = Readable.from([reportContent]);

  const res = await drive.files.create({
    requestBody: {
      name: fileName,
      mimeType: "text/markdown",
      parents: [folder],
    },
    media: {
      mimeType: "text/markdown",
      body: fileStream,
    },
    fields: "id, name, webViewLink",
  });

  const fileId = res.data.id ?? "";
  const webViewLink = res.data.webViewLink ?? "";

  return {
    fileId,
    fileName,
    webViewLink,
    folderId: folder,
  };
}

// ---------------------------------------------------------------
// Report Builder
// ---------------------------------------------------------------
function buildMarkdownReport(record: AnalysisRecord): string {
  const verdict = record.ready_to_merge
    ? "✅ READY TO MERGE"
    : "❌ NEEDS CHANGES";

  const jiraSection = record.jira_key
    ? `- **Jira Ticket:** ${record.jira_key}${record.jira_summary ? ` — ${record.jira_summary}` : ""}`
    : "";

  const mr = record.mr_snapshot as unknown as Record<string, unknown> | null;
  const mrUrl = mr?.raw_url ? `\n- **MR URL:** ${mr.raw_url}` : "";

  return [
    `# AI Code Review Report`,
    ``,
    `## Overview`,
    `- **MR Key:** ${record.mr_key}`,
    `- **MR Title:** ${record.mr_title ?? "N/A"}`,
    jiraSection,
    `- **Analyst:** ${record.analyst}`,
    `- **Analyzed At:** ${record.analyzed_at}`,
    `- **Platform:** ${record.platform}`,
    mrUrl,
    ``,
    `## Verdict`,
    ``,
    `**${verdict}**`,
    ``,
    `## Review Summary`,
    ``,
    record.review_summary,
    ``,
    `---`,
    `*Generated by mcp-bridge-tool*`,
  ]
    .filter((line) => line !== undefined)
    .join("\n");
}

function buildFileName(record: AnalysisRecord): string {
  const safeKey = record.mr_key.replace(/[^a-zA-Z0-9-_#]/g, "_");
  const date = record.analyzed_at.split("T")[0];
  return `review-${safeKey}-${date}.md`;
}
